name: Nightly Cleanup
on:
  push:
    branches:
    - main
 # schedule:
    #- cron: '00 12 */5 * *'
   # - cron: '*/30 * * * *'

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ENABLED: 'true'
  
  # Keeps only $MAX_NIGHTLY most recent nightly releases.
  MAX_NIGHTLY: 1

  # Remove associated nightly git tag
  CLEAR_TAG: 'false'
jobs:
  clean:
    name: Prune nightly releases
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ["cron"]
    steps:
      - name: Logs
        run: |
          echo "ok"
      - name: Releases
        run: |
          MAX=$((MAX_NIGHTLY))
          if [ $ENABLED == 'true' ]; then \
            gh api --paginate repos/dragonhunt02/${{ matrix.repo }}/releases | \
            jq -r '[.[] | select(.tag_name | contains("-nightly-"))] | .[$ENV.MAX_NIGHTLY:] | .[] | [.id, .tag_name] | debug | @tsv' | \
            while read -r id tag; do
                echo "Deleting release id: $id, tag: $tag";
              # gh api -X DELETE "repos/dragonhunt02/${{ matrix.repo }}/releases/$id"
              if [ $CLEAR_TAG == 'true' ]; then
                echo "Deleting tag: $tag";
              # gh api -X DELETE "repos/dragonhunt02/${{ matrix.repo }}/git/refs/$tag"
              fi
            done;
          else
          echo "Scheduled nightly cleanup is disabled."
          fi
 #> test.txt && cat test.txt #\
 #$tag =~ .*
 #-nightly-.*
