name: ♻️ Nightly Cleanup
on:
  push:
    branches:
    - main
 # schedule:
    #- cron: '00 12 */5 * *'
  #  - cron: '*/5 * * * *'

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ENABLED: 'true'
  
  # Keeps only $MAX_NIGHTLY most recent nightly releases.
  MAX_NIGHTLY: 1

  # Remove associated nightly git tag
  CLEAR_TAG: 'true'
jobs:
  clean:
    name: Prune nightly releases
    runs-on: ubuntu-latest
    if: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        repo: ["cron"]
    steps:
      - name: Releases
        run: |
          if [ $ENABLED == 'true' ]; then
            gh api --paginate repos/dragonhunt02/${{ matrix.repo }}/releases | \
            jq -r '[.[] | select(.tag_name | contains("-nightly-"))] | .['${MAX_NIGHTLY}':] | .[] | [.id, .tag_name] | @tsv' | \
            while read -r id tag; do
                echo "Deleting release id: $id, tag: $tag";
                gh api -X DELETE "repos/dragonhunt02/${{ matrix.repo }}/releases/$id"
              if [ $CLEAR_TAG == 'true' ]; then
                echo "Deleting tag: $tag";
                gh api -X DELETE "repos/dragonhunt02/${{ matrix.repo }}/git/refs/tags/$tag"
              fi
            done;
          else
            echo "Scheduled nightly cleanup is disabled.";
          fi
