name: Nightly Cleanup
on:
  push:
    branches:
    - main
 # schedule:
    #- cron: '00 12 */5 * *'
   # - cron: '*/30 * * * *'

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ENABLED: 'true'
jobs:
  clean:
    name: Prune nightly releases
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ["cron"]
    steps:
      - name: Logs
        run: |
          echo "ok"
      - name: Releases
        run: |
          if [ $ENABLED == 'true' ]; then \
            
            gh api --paginate repos/dragonhunt02/${{ matrix.repo }}/releases | \
            jq -r '[.[] | select(.tag_name | contains("-nightly-"))] | [1:] | debug | .[] | [.id, .tag_name] | .[] | @tsv' | \
            while read -r id tag; do
              if [[ $tag =~ .* ]]; then
                echo "Deleting release id: $id, tag: $tag";
              # gh api -X DELETE "repos/dragonhunt02/${{ matrix.repo }}/releases/$id"
              fi
            done;
          fi
 #> test.txt && cat test.txt #\
 #-nightly-.*
